"""Create user table

Revision ID: 0936117b5325
Revises: 8c66db11b287
Create Date: 2020-01-23 16:27:05.888635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0936117b5325'
down_revision = '8c66db11b287'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=280), nullable=True),
    sa.Column('email', sa.String(length=280), nullable=True),
    sa.Column('api_key', sa.String(length=280), nullable=True),
    sa.Column('tweets', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tweets'], ['tweets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
