"""update relationship between user and tweets

Revision ID: 8446afd5eeac
Revises: f0c8a2aa7a51
Create Date: 2020-01-23 17:03:43.110041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8446afd5eeac'
down_revision = 'f0c8a2aa7a51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tweets_user_fkey', 'tweets', type_='foreignkey')
    op.create_foreign_key(None, 'tweets', 'users', ['user'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tweets', type_='foreignkey')
    op.create_foreign_key('tweets_user_fkey', 'tweets', 'tweets', ['user'], ['id'])
    # ### end Alembic commands ###
