"""updqte relationship between user and tweets

Revision ID: f0c8a2aa7a51
Revises: 0936117b5325
Create Date: 2020-01-23 16:33:19.661324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0c8a2aa7a51'
down_revision = '0936117b5325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweets', sa.Column('user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tweets', 'tweets', ['user'], ['id'])
    op.drop_constraint('users_tweets_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'tweets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tweets', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_tweets_fkey', 'users', 'tweets', ['tweets'], ['id'])
    op.drop_constraint(None, 'tweets', type_='foreignkey')
    op.drop_column('tweets', 'user')
    # ### end Alembic commands ###
